### ISSUE TITLE
Plex/TVHeadend Current Version not working HTTP 422

### ISSUE THREAD

**Issue by regnets** [jkaberg/tvhProxy#20]
Plex Version: 1.7.2.3878
TVHeadend Version: 4.3-210~g7644886

tvhProxy Log:
::ffff:10.0.0.236 - - [2017-06-12 13:45:18] "GET /discover.json HTTP/1.0" 200 422 0.001799
::ffff:10.0.0.236 - - [2017-06-12 13:45:18] "GET /lineup_status.json HTTP/1.0" 200 234 0.001017
::ffff:10.0.0.236 - - [2017-06-12 13:45:18] "GET /discover.json HTTP/1.0" 200 422 0.000750
::ffff:10.0.0.236 - - [2017-06-12 13:45:18] "GET /lineup_status.json HTTP/1.0" 200 234 0.000638

Plex is unable to connect and can't perform a channel search.

**Comment by nikdoof** [comment]
This is a current issue, but if you provide the manual address/port then "Continue" button should enable without actually showing a new device being found, you'll probably notice in the background that a popup appears saying new DVR devices have been discovered.

**Comment by regnets** [comment]
Thanks for the response, your provided work arround doesn't work for TVH 4.3 this only works for 4.0.9 on my machine.

**Comment by DJFliX** [comment]
I'm actually receiving the same response:
`::ffff:192.168.1.5 - - [2017-06-17 22:09:07] "GET /discover.json HTTP/1.0" 200 422 0.001405
::ffff:192.168.1.5 - - [2017-06-17 22:09:07] "GET /lineup_status.json HTTP/1.0" 200 234 0.001331
::ffff:192.168.1.5 - - [2017-06-17 22:09:07] "GET /discover.json HTTP/1.0" 200 422 0.001289
::ffff:192.168.1.5 - - [2017-06-17 22:09:07] "GET /lineup_status.json HTTP/1.0" 200 234 0.001192
An error occured: ValueError('No JSON object could be decoded',)
[2017-06-17 22:09:09,592] ERROR in app: Exception on /lineup.json [GET]
Traceback (most recent call last):
  File "/home/flix/tvhProxy/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/flix/tvhProxy/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/flix/tvhProxy/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/flix/tvhProxy/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/flix/tvhProxy/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "tvhProxy.py", line 51, in lineup
    for c in _get_channels():
TypeError: 'NoneType' object is not iterable`

Running Plex Version 1.7.2.3878, TVH version 4.2.2-49 and latest master from tvhProxy.

**Comment by matteggleton89** [comment]
Same issue here, Plex will find the dvr when using IP and Port number, but when scanning for channels Plex gives error" There was a problem getting the channels for your device"

Is there any other current workaround or version combination that works?

tvhProxy: Latest master
Tvheadend: 4.0.9 (tried 4.2, same issue)
Plex: 1.8.2.4209

tvhProxy error:
An error occured: ValueError('No JSON object could be decoded',)
[2017-09-05 11:59:27,982] ERROR in app: Exception on /lineup.json [GET]
Traceback (most recent call last):
  File "/home/matt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/matt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/matt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/matt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/matt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "tvhProxy.py", line 52, in lineup
    for c in _get_channels():
TypeError: 'NoneType' object is not iterable
::ffff:192.168.1.12 - - [2017-09-05 11:59:27] "GET /lineup.json HTTP/1.0" 500 431 0.005166

**Comment by hirenshah** [comment]
Anyone manage to figure this out? I have tvheadend and tvhproxy running on the same Ubuntu VM but they cannot connect to each other.

**Comment by jwrober** [comment]
https://github.com/jkaberg/tvhProxy/issues/46#issuecomment-366240259
