### ISSUE TITLE
An error occured: ValueError('Invalid IPv6 URL',)

### ISSUE THREAD

**Issue by rafuz** [jkaberg/tvhProxy#37]
I get this error when I try to connect from Plex to the tvhProxy.
Any ideas?

`::ffff:127.0.0.1 - - [2017-10-10 16:43:54] "GET /discover.json HTTP/1.0" 200 454 0.001148
::ffff:127.0.0.1 - - [2017-10-10 16:43:54] "GET /lineup_status.json HTTP/1.0" 200 234 0.000730
::ffff:127.0.0.1 - - [2017-10-10 16:43:54] "GET /discover.json HTTP/1.0" 200 454 0.000725
::ffff:127.0.0.1 - - [2017-10-10 16:43:54] "GET /lineup_status.json HTTP/1.0" 200 234 0.000727
An error occured: ValueError('Invalid IPv6 URL',)
[2017-10-10 16:44:01,094] ERROR in app: Exception on /lineup.json [GET]
Traceback (most recent call last):
  File "/opt/tvhProxy/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/tvhProxy/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/tvhProxy/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/tvhProxy/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/tvhProxy/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/tvhProxy/tvhProxy.py", line 54, in lineup
    for c in _get_channels():
TypeError: 'NoneType' object is not iterable
::ffff:127.0.0.1 - - [2017-10-10 16:44:01] "GET /lineup.json HTTP/1.0" 500 431 0.004618
`

**Comment by lcasey001** [comment]
Did you ever figure out the solution? I am having this same issue running it from within docker.

**Comment by EnorMOZ** [comment]
Did you ever figure out a solution ? I am having the same issue running it from within docker.

**Comment by rafuz** [comment]
Yes I did. 
There were special characters in tvheadend password that broke the address string.
Just use a password with only letters and number and should be ok.
