### ISSUE TITLE
lineup.json causes 500

### ISSUE THREAD

**Issue by martzuk** [jkaberg/tvhProxy#8]
```
(venv)root@home:/home/tvh/tvhProxy# python tvhProxy.py
An error occured: ValueError('No JSON object could be decoded',)
[2017-03-01 21:39:44,343] ERROR in app: Exception on /lineup.json [GET]
Traceback (most recent call last):
  File "/home/tvh/tvhProxy/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tvh/tvhProxy/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tvh/tvhProxy/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tvh/tvhProxy/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tvh/tvhProxy/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "tvhProxy.py", line 49, in lineup
    for c in _get_channels():
TypeError: 'NoneType' object is not iterable
```

**Comment by gpenverne** [comment]
Try with python3 ;)

**Comment by jkaberg** [comment]
```ValueError('No JSON object could be decoded',)``` means it canno't connect to your Tvheadend instance.
